routes/web.php
<?php

Auth::routes();
Route::get('/', 'PageController@index')->name('index');
Route::get('contact', 'PageController@contact')->name('contact');
Route::get('about-us', 'PageController@aboutUs')->name('about_us');
Route::get('advertising', 'PageController@advertising')->name('advertising');
Route::get('faq', 'PageController@faq')->name('faq');
Route::get('privacy', 'PageController@privacy')->name('privacy');

Route::get('blogs', 'PageController@blogs')->name('blogs');
Route::get('blog/{slug}', 'PageController@blogPost')->name('blog_post');

Route::get('apoteke', 'PageController@pharmacies')->name('pharmacies');
Route::get('a/{slug}', 'PageController@pharmacy')->name('pharmacy');

Route::get('proizvodi', 'PageController@products')->name('products');
Route::get('p/{slug}', 'PageController@product')->name('product');

Route::get('profil/{slug}', 'PageController@employee')->name('employee');
Route::get('search', 'PageController@search')->name('search');


Route::get('home', 'HomeController@index');

Route::get('lc-admin', 'Laracode\AdminController@index')->name('lc-admin');

Route::group(['as' => 'lc-admin.', 'prefix' => 'lc-admin', 'middleware' => ['auth', 'permission:admin panel']], function () {

    Route::resource('groups', 'GroupController')->middleware('permission:group read');

    Route::resource('pharmacies', 'PharmacyController')->middleware('permission:pharmacy read');

    Route::post('drugs/import', 'DrugController@import')->name('drugs.import');
    Route::resource('drugs', 'DrugController')->middleware('permission:drug read');
    Route::resource('drug-pharmacy', 'DrugPharmacyController')
        ->parameters(['drug-pharmacies' => 'drug'])
        ->middleware('permission:drug pharmacy read');

    Route::resource('employees', 'EmployeeController')->middleware('permission:employee read');

    Route::resource('job-board', 'JobBoardController')->middleware('permission:job board read');

    Route::resource('group-pharmacies', 'GroupPharmaciesController')->parameters([
        'group-pharmacies' => 'group'
    ])->except(['index', 'create', 'store']);

    Route::resource('user-pharmacies', 'UserPharmaciesController')->parameters([
        'user-pharmacies' => 'user'
    ]);

    Route::resource('sliders', 'SliderController')->middleware('role:super admin');

    Route::resource('blogs', 'BlogController')->middleware('permission:blog read');

    Route::post('upload/{path}', 'ImageController@store')->name('images.store');
});

Route::group(['as' => 'lc-admin.', 'prefix' => 'lc-admin', 'middleware' => ['auth', 'permission:admin panel'], 'namespace' => 'Laracode'], function () {

    Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::resource('roles', 'RoleController', ['except' => ['show', 'edit']]);
    Route::resource('permissions', 'PermissionController', ['except' => ['show', 'edit']]);

    Route::resource('users', 'UserController')->middleware('permission:super admin');

    Route::get('languages', 'LanguageController@index')->name('languages');
    Route::post('languages/{name}', 'LanguageController@store')->name('store-language');
    Route::get('set-language/{language}', 'LanguageController@update')->name('set-language');

    Route::get('activity-log', 'AdminController@activityLog')->name('activity-log');

    Route::post('newsletter', 'NewsletterController@store')->name('store-newsletter');
});

app/Employee.php
<?php

namespace App;

use App\Pharmacy;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];
    
    protected $guarded = [];
    
    public function pharmacies()
    {
        return $this->belongsToMany(Pharmacy::class);
    }
    
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\Pharmacy;
use App\Services\FileService;
use Illuminate\Http\Request;
use App\Http\Requests\EmployeeRequest;
use Yajra\DataTables\Facades\DataTables;

class EmployeeController extends Controller
{
    public function __construct(FileService $fileService)
    {
        $this->authorizeResource(Employee::class);

        $this->fileService = $fileService;
    }

    public function index()
    {
        if (request()->ajax()) {
            return DataTables::eloquent(
                Employee::query()
                    ->with(['pharmacies', 'pharmacies.location'])
                    ->latest()
                )->addColumn('action', function ($employee) {
                   return view('lc-admin.employees.datatable-action', compact('employee'));
                })->make(true);
        }

        return view('lc-admin.employees.index');
    }

    public function create()
    {
        return view('lc-admin.employees.create')->with(
            'pharmacies', Pharmacy::with('location')->get()
        );
    }

    /**
     * @param  \App\Http\Requests\EmployeeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        $fileName = $this->fileService->upload($request->image, 'employees');

        $employee = Employee::create(
            array_merge(
                $request->except(['pharmacies', 'image']),
                ['image' => $fileName]
            )
        );

        $employee->pharmacies()
            ->sync($request->pharmacies);

        return redirect()->route('lc-admin.employees.index');
    }

    public function show(Employee $employee)
    {

    }

    public function edit(Employee $employee)
    {
        return view('lc-admin.employees.edit')->with([
            'employee' => $employee,
            'pharmacies' => Pharmacy::all(),
        ]);
    }

    /**
     * @param  \App\Employee  $employee
     * @param  \App\Http\Requests\EmployeeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Employee $employee, EmployeeRequest $request)
    {
        $imageArray = [];

        if ($request->has('image')) {
            $fileName = $this->fileService->uploadAndDelete($employee->image, $request->image, 'employees');
            $imageArray = ['image' => $fileName];
        }

        $employee->update(
            array_merge(
                $request->except(['pharmacies', 'image']),
                $imageArray
            )
        );

        $employee->pharmacies()
            ->sync($request->pharmacies);

        return redirect()->route('lc-admin.employees.index');
    }

    public function destroy(Employee $employee)
    {
        $employee->delete();

        $this->fileService->delete($employee->image);

        return notify('success-solid-active', 'Uspešno je obrisan zaposleni');
    }

}

resources/views/lc-admin/employees/create.blade.php
@extends('lc-admin.layouts.master')
@section('title', __('New Employee'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('New Employee') }}</h3>

            <div class="ks-controls">
                {{ Breadcrumbs::render('lc-admin.employees.create') }}


                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-nav-body-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6 ks-panels-column-section">
                            <div class="card">
                                <div class="card-block">
                                    <h5 class="card-title">{{ __('New Employee') }}</h5>
                                    <form action="{{ route('lc-admin.employees.store') }}" method="POST" enctype="multipart/form-data">
                                        @csrf
                                        <div class="form-group row">
                                            <label for="first-name-input" class="col-sm-3 form-control-label">{{ __('First name') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="text"
                                                    name="first_name"
                                                    class="form-control {{ $errors->has('first_name') ? 'is-invalid' : '' }}"
                                                    id="first-name-input"
                                                    placeholder="{{ __('Employee first name') }}"
                                                    value="{{ old('first_name') }}"
                                                >
                                                @if($errors->has('first_name'))
                                                    <small class="text-danger">{{ $errors->first('first_name') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="last-name-input" class="col-sm-3 form-control-label">{{ __('Last name') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="text"
                                                    name="last_name"
                                                    class="form-control {{ $errors->has('last_name') ? 'is-invalid' : '' }}"
                                                    id="last-name-input"
                                                    placeholder="{{ __('Employee last name') }}"
                                                    value="{{ old('last_name') }}"
                                                >
                                                @if($errors->has('last_name'))
                                                    <small class="text-danger">{{ $errors->first('last_name') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div>
                                            <div class="preview-div col-md-9 mb-3 ml-auto" hidden>
                                                <img class="preview-image img-fluid" src="#">
                                            </div>
                                            <div class="form-group row">
                                                <label for="image-input" class="col-sm-3 form-control-label">{{ __('Image') }}</label>
                                                <div class="col-sm-9">
                                                    <label class="btn btn-primary ks-btn-file">
                                                        <span class="la la-cloud-upload ks-icon"></span>
                                                        <span class="ks-text">{{ __('Choose file') }}</span>
                                                        <input
                                                            class="preview-input"
                                                            type="file"
                                                            name="image"
                                                        >
                                                    </label>
                                                    @if($errors->has('image'))
                                                        <small class="text-danger">{{ $errors->first('image') }}</small>
                                                    @endif
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="description-input" class="col-sm-3 form-control-label">{{ __('Description') }}<span class="text-danger"> *</span></label>
                                            <div class="col-sm-9">
                                                <textarea
                                                    name="description"
                                                    id="description-input"
                                                    class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}"
                                                    placeholder="{{ __('Description') }}"
                                                >{{ old('description') }}</textarea>
                                                @if($errors->has('description'))
                                                    <small class="text-danger">{{ $errors->first('description') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="pharmacies-select" class="col-sm-3 form-control-label">{{ __('Pharmacies') }}</label>
                                            <div class="col-sm-9">
                                                <select
                                                    class="form-control multiselect2-pharmacies {{ $errors->has('pharmacies') ? 'is-invalid' : '' }}"
                                                    name="pharmacies[]"
                                                    id="pharmacies-select"
                                                    multiple
                                                >
                                                    @foreach($pharmacies as $pharmacy)
                                                        <option value="{{ $pharmacy->id }}">
                                                            {{ $pharmacy->name . ' - ' . $pharmacy->address . ', ' . $pharmacy->location->name }}
                                                        </option>
                                                    @endforeach
                                                </select>
                                                @if($errors->has('pharmacies'))
                                                    <small class="text-danger">{{ $errors->first('pharmacies') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <button class="float-right btn btn-primary">{{ __('Create') }}</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('external-js')
<script type="text/javascript">
$(document).ready(function() {
    $('.multiselect2-pharmacies').select2({
        placeholder: '{{ __('Select pharmacies') }}'
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('.preview-image').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $(".preview-input").change(function() {
        $('.preview-div').attr('hidden', false);
        readURL(this);
    });
});
</script>
@endsection

resources/views/lc-admin/employees/datatable-action.blade.php
<div class="ks-controls">
    <a href="{{ route('lc-admin.employees.edit', ['employees' => $employee]) }}">
        <button type="button" class="btn btn-primary ks-light ks-no-text" style="line-height: 38px;">
            <span class="la la-pencil ks-icon"></span>
        </button>
    </a>
    <button class="btn btn-danger ks-light ks-no-text delete-employee" data-id="{{ $employee->id }}" data-name="{{ $employee->first_name . ' ' . $employee->last_name }}" style="line-height: 38px;">
        <span class="la la-trash-o ks-icon"></span>
    </button>
</div>

resources/views/lc-admin/employees/edit.blade.php
@extends('lc-admin.layouts.master')
@section('title', __('Edit Employee'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('Edit Employee') }}</h3>

            <div class="ks-controls">
                {{ Breadcrumbs::render('lc-admin.employees.edit', $employee) }}


                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-nav-body-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6 ks-panels-column-section">
                            <div class="card">
                                <div class="card-block">
                                    <h5 class="card-title">{{ __('Edit Employee') }}</h5>
                                    <form id="form-edit-employee" action="{{ route('lc-admin.employees.update', ['employee' => $employee->id]) }}" method="POST" enctype="multipart/form-data">
                                        @method('PUT')
                                        @csrf
                                        <div class="form-group row">
                                            <label for="first-name-input" class="col-sm-3 form-control-label">{{ __('First name') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="text"
                                                    name="first_name"
                                                    class="form-control {{ $errors->has('first_name') ? 'is-invalid' : '' }}"
                                                    id="first-name-input"
                                                    placeholder="{{ __('Employee first name') }}"
                                                    value="{{ old('first_name', $employee->first_name) }}"
                                                >
                                                @if($errors->has('first_name'))
                                                    <small class="text-danger">{{ $errors->first('first_name') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="last-name-input" class="col-sm-3 form-control-label">{{ __('Last name') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="text"
                                                    name="last_name"
                                                    class="form-control {{ $errors->has('last_name') ? 'is-invalid' : '' }}"
                                                    id="last-name-input"
                                                    placeholder="{{ __('Employee last name') }}"
                                                    value="{{ old('last_name', $employee->last_name) }}"
                                                >
                                                @if($errors->has('last_name'))
                                                    <small class="text-danger">{{ $errors->first('last_name') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div>
                                            <div class="col-md-9 mb-3 ml-auto">
                                                <img class="preview-image img-fluid" src="{{ file_path($employee->image) }}"  alt="{{ $employee->first_name . '\'s photo'}}">
                                            </div>
                                            <div class="form-group row">
                                                <label for="image-input" class="col-sm-3 form-control-label">{{ __('Image') }}</label>
                                                <div class="col-sm-9">
                                                    <label class="btn btn-primary ks-btn-file">
                                                        <span class="la la-cloud-upload ks-icon"></span>
                                                        <span class="ks-text">{{ __('Choose file') }}</span>
                                                        <input
                                                            class="preview-input"
                                                            type="file"
                                                            name="image"
                                                        >
                                                    </label>
                                                    @if($errors->has('image'))
                                                        <small class="text-danger">{{ $errors->first('image') }}</small>
                                                    @endif
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="description-input" class="col-sm-3 form-control-label">{{ __('Description') }}<span class="text-danger"> *</span></label>
                                            <div class="col-sm-9">
                                                <textarea
                                                    name="description"
                                                    id="description-input"
                                                    class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}"
                                                    placeholder="{{ __('Description') }}"
                                                >{{ old('description', $employee->description) }}</textarea>
                                                @if($errors->has('description'))
                                                    <small class="text-danger">{{ $errors->first('description') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="pharmacies-select" class="col-sm-3 form-control-label">{{ __('Pharmacies') }}</label>
                                            <div class="col-sm-9">
                                                <select
                                                    class="form-control multiselect2-pharmacies {{ $errors->has('pharmacies') ? 'is-invalid' : '' }}"
                                                    name="pharmacies[]"
                                                    id="pharmacies-select"
                                                    multiple
                                                >
                                                    @foreach($pharmacies as $pharmacy)
                                                        <option value="{{ $pharmacy->id }}" @if($employee->pharmacies->contains($pharmacy)) selected @endif>
                                                            {{ $pharmacy->name . ' - ' . $pharmacy->address . ', ' . $pharmacy->location->name }}
                                                        </option>
                                                    @endforeach
                                                </select>
                                                @if($errors->has('pharmacies'))
                                                    <small class="text-danger">{{ $errors->first('pharmacies') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <button class="float-right btn btn-primary btn-edit-employee">{{ __('Update') }}</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('external-js')
<script type="text/javascript">
$(document).ready(function() {
    $('.multiselect2-pharmacies').select2({
        placeholder: '{{ __('Select pharmacies') }}'
    });

    $('.btn-edit-employee').on('click', function (e) {
        e.preventDefault();

        $.confirm({
            title: 'Pažnja!',
            content: 'Da li želite da sačuvate izmjene?',
            type: 'warning',
            buttons: {
                confirm: {
                    text: 'OK',
                    btnClass: 'btn-warning',
                    action: function () {
                        $('#form-edit-employee').submit();
                    }
                },
                cancel: function () {

                }
            }
        });
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('.preview-image').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $(".preview-input").change(function() {
        // $('.preview-div').attr('hidden', false);
        readURL(this);
    });
});
</script>
@endsection