routes/web.php
<?php

Auth::routes();
Route::get('/', 'PageController@index')->name('index');
Route::get('contact', 'PageController@contact')->name('contact');
Route::get('about-us', 'PageController@aboutUs')->name('about_us');
Route::get('advertising', 'PageController@advertising')->name('advertising');
Route::get('faq', 'PageController@faq')->name('faq');
Route::get('privacy', 'PageController@privacy')->name('privacy');

Route::get('blogs', 'PageController@blogs')->name('blogs');
Route::get('blog/{slug}', 'PageController@blogPost')->name('blog_post');

Route::get('apoteke', 'PageController@pharmacies')->name('pharmacies');
Route::get('a/{slug}', 'PageController@pharmacy')->name('pharmacy');

Route::get('proizvodi', 'PageController@products')->name('products');
Route::get('p/{slug}', 'PageController@product')->name('product');

Route::get('profil/{slug}', 'PageController@employee')->name('employee');
Route::get('search', 'PageController@search')->name('search');


Route::get('home', 'HomeController@index');

Route::get('lc-admin', 'Laracode\AdminController@index')->name('lc-admin');

Route::group(['as' => 'lc-admin.', 'prefix' => 'lc-admin', 'middleware' => ['auth', 'permission:admin panel']], function () {

    Route::resource('groups', 'GroupController')->middleware('permission:group read');

    Route::resource('pharmacies', 'PharmacyController')->middleware('permission:pharmacy read');

    Route::post('drugs/import', 'DrugController@import')->name('drugs.import');
    Route::resource('drugs', 'DrugController')->middleware('permission:drug read');
    Route::resource('drug-pharmacy', 'DrugPharmacyController')
        ->parameters(['drug-pharmacies' => 'drug'])
        ->middleware('permission:drug pharmacy read');

    Route::resource('employees', 'EmployeeController')->middleware('permission:employee read');

    Route::resource('job-board', 'JobBoardController')->middleware('permission:job board read');

    Route::resource('group-pharmacies', 'GroupPharmaciesController')->parameters([
        'group-pharmacies' => 'group'
    ])->except(['index', 'create', 'store']);

    Route::resource('user-pharmacies', 'UserPharmaciesController')->parameters([
        'user-pharmacies' => 'user'
    ]);

    Route::resource('sliders', 'SliderController')->middleware('role:super admin');

    Route::resource('blogs', 'BlogController')->middleware('permission:blog read');

    Route::post('upload/{path}', 'ImageController@store')->name('images.store');
});

Route::group(['as' => 'lc-admin.', 'prefix' => 'lc-admin', 'middleware' => ['auth', 'permission:admin panel'], 'namespace' => 'Laracode'], function () {

    Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::resource('roles', 'RoleController', ['except' => ['show', 'edit']]);
    Route::resource('permissions', 'PermissionController', ['except' => ['show', 'edit']]);

    Route::resource('users', 'UserController')->middleware('permission:super admin');

    Route::get('languages', 'LanguageController@index')->name('languages');
    Route::post('languages/{name}', 'LanguageController@store')->name('store-language');
    Route::get('set-language/{language}', 'LanguageController@update')->name('set-language');

    Route::get('activity-log', 'AdminController@activityLog')->name('activity-log');

    Route::post('newsletter', 'NewsletterController@store')->name('store-newsletter');
});

app/JobBoard.php
<?php

namespace App;

use App\Group;
use App\Location;
use App\User;
use Illuminate\Database\Eloquent\Model;

class JobBoard extends Model
{
    protected $guarded = [];

    public function location() 
    {
        return $this->belongsTo(Location::class);
    }

    public function group() 
    {
        return $this->belongsTo(Group::class);
    }

    public function user() 
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/JobBoardController.php
<?php

namespace App\Http\Controllers;

use App\Group;
use App\Http\Requests\JobBoardRequest;
use App\JobBoard;
use App\Location;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;

class JobBoardController extends Controller
{
    /**
     * Creates new controller instance
     */
    function __construct()
    {
        $this->authorizeResource(JobBoard::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            return DataTables::eloquent(
                JobBoard::query()
                    ->with(['user', 'group'])
                    ->latest()
                )->addColumn('action', function ($jobBoard) {
                   return view('lc-admin.job-board.datatable-action', compact('jobBoard'));
               })->make(true);
        }

        return view('lc-admin.job-board.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('lc-admin.job-board.create')->with([
            'locations' => Location::all(),
            'groups' => Group::all(),
            'users' => User::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(JobBoardRequest $request)
    {
        if (Auth::user()->hasRole('super admin')) {
            JobBoard::create($request->all());
        } else {
            Auth::user()->jobBoards()
                ->create($request->except('user_id'));
        }

        return redirect()->route('lc-admin.job-board.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\JobBoard  $jobBoard
     * @return \Illuminate\Http\Response
     */
    public function show(JobBoard $jobBoard)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\JobBoard  $jobBoard
     * @return \Illuminate\Http\Response
     */
    public function edit(JobBoard $jobBoard)
    {
        return view('lc-admin.job-board.edit')->with([
            'jobBoard' => $jobBoard,
            'users' => User::all(),
            'locations' => Location::all(),
            'groups' => Group::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\JobBoard  $jobBoard
     * @return \Illuminate\Http\Response
     */
    public function update(JobBoardRequest $request, JobBoard $jobBoard)
    {
        if (Auth::user()->hasRole('super admin')) {
            $jobBoard->update($request->all());
        } else {
            Auth::user()->jobBoards()
                ->update($request->except('user_id'));
        }

        return redirect()->route('lc-admin.job-board.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\JobBoard  $jobBoard
     * @return \Illuminate\Http\Response
     */
    public function destroy(JobBoard $jobBoard)
    {
        $jobBoard->delete();

        return notify('success-solid-active', __('Uspešno je obrisan oglas za posao'));
    }
}

resources/views/lc-admin/job-board/create.blade.php
@extends('lc-admin.layouts.master')
@section('title', __('New Job'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('New Job') }}</h3>

            <div class="ks-controls">
                {{ Breadcrumbs::render('lc-admin.job-board.create') }}


                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-nav-body-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6 ks-panels-column-section">
                            <div class="card">
                                <div class="card-block">
                                    <h5 class="card-title">{{ __('New Job') }}</h5>
                                    <form 
                                        action="{{ route('lc-admin.job-board.store') }}" 
                                        method="POST" 
                                        enctype="multipart/form-data"
                                    >
                                        @csrf
                                        <div class="form-group row">
                                            <label for="title-input" class="col-sm-3 form-control-label">{{ __('Title') }}</label>
                                            <div class="col-sm-9">
                                                <textarea
                                                    name="title"
                                                    class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}"
                                                    id="title-input"
                                                    placeholder="{{ __('Job title') }}"
                                                >{{ old('title') }}</textarea>
                                                @if($errors->has('title'))
                                                    <small class="text-danger">{{ $errors->first('title') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="content-input" class="col-sm-3 form-control-label">{{ __('Content') }}</label>
                                            <div class="col-sm-9">
                                                <textarea
                                                    name="content"
                                                    class="form-control {{ $errors->has('content') ? 'is-invalid' : '' }}"
                                                    id="content-input"
                                                    placeholder="{{ __('Job content') }}"
                                                    rows="10"
                                                >{{ old('content') }}</textarea>
                                                @if($errors->has('content'))
                                                    <small class="text-danger">{{ $errors->first('content') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="position-input" class="col-sm-3 form-control-label">{{ __('Position') }}</label>
                                            <div class="col-sm-9">
                                                <textarea
                                                    name="position"
                                                    class="form-control {{ $errors->has('position') ? 'is-invalid' : '' }}"
                                                    id="position-input"
                                                    placeholder="{{ __('Job position') }}"
                                                >{{ old('position') }}</textarea>
                                                @if($errors->has('position'))
                                                    <small class="text-danger">{{ $errors->first('position') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="position-input" class="col-sm-3 form-control-label">{{ __('Executors Count') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="number"
                                                    min="0"
                                                    name="executor_count"
                                                    class="form-control {{ $errors->has('executor_count') ? 'is-invalid' : '' }}"
                                                    id="executor-count-input"
                                                    value="{{ old('executor_count', 1) }}"
                                                >
                                                @if($errors->has('executor_count'))
                                                    <small class="text-danger">{{ $errors->first('executor_count') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="location-input" class="col-sm-3 form-control-label">
                                                {{ __('Location') }}<span class="text-danger"> *</span>
                                            </label>
                                            <div class="col-sm-9">
                                                <select
                                                    class="form-control {{ $errors->has('location_id') ? 'is-invalid' : '' }}"
                                                    name="location_id"
                                                    id="location-input"
                                                >
                                                    <option disabled selected>{{ __('Select location') }}</option>
                                                    @foreach ($locations as $location)
                                                        <option value="{{ $location->id }}">{{ $location->name }}</option>
                                                    @endforeach
                                                </select>
                                                @if($errors->has('location_id'))
                                                    <small class="text-danger">{{ $errors->first('location_id') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="group-input" class="col-sm-3 form-control-label">
                                                {{ __('Group') }}
                                            </label>
                                            <div class="col-sm-9">
                                                <select
                                                    class="form-control"
                                                    name="group_id"
                                                    id="group-input"
                                                >
                                                    @foreach ($groups as $group)
                                                        <option value="{{ $group->id }}">{{ $group->name }}</option>
                                                    @endforeach
                                                </select>
                                                @if($errors->has('groups'))
                                                    <small class="text-danger">{{ $errors->first('groups') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        @if(Auth::user()->hasRole('super admin'))
                                            <div class="form-group row">
                                                <label for="user-input" class="col-sm-3 form-control-label">
                                                    {{ __('User') }}
                                                </label>
                                                <div class="col-sm-9">
                                                    <select
                                                        class="form-control {{ $errors->has('users') ? 'is-invalid' : '' }}"
                                                        name="user_id"
                                                        id="user-input"
                                                    >
                                                        @foreach($users as $user)
                                                            <option value="{{ $user->id }}">{{ $user->first_name . ' ' . $user->last_name . ', ' . $user->email }}</option>
                                                        @endforeach
                                                    </select>
                                                    @if($errors->has('users'))
                                                        <small class="text-danger">{{ $errors->first('users') }}</small>
                                                    @endif
                                                </div>
                                            </div>
                                        @endif

                                        <button class="float-right btn btn-primary">{{ __('Submit') }}</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('external-js')
<script type="text/javascript">
$(document).ready(function() {
    $('.multiselect2-groups').select2({
        placeholder: '{{ __('Select groups') }}'
    });

    $('.multiselect2-users').select2({
        placeholder: '{{ __('Select users') }}'
    });
});
</script>
@endsection

resources/views/lc-admin/job-board/edit.blade.php
@extends('lc-admin.layouts.master')
@section('title', __('Edit Job'))
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('Edit Job') }}</h3>

            <div class="ks-controls">
                {{ Breadcrumbs::render('lc-admin.job-board.edit', $jobBoard) }}


                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-nav-body-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6 ks-panels-column-section">
                            <div class="card">
                                <div class="card-block">
                                    <h5 class="card-title">{{ __('Edit Job') }}</h5>
                                    <form 
                                        id="form-edit-job" 
                                        action="{{ route('lc-admin.job-board.update', ['job_board' => $jobBoard]) }}" 
                                        method="POST" 
                                    >
                                        @method('PUT')
                                        @csrf
                                        <div class="form-group row">
                                            <label for="title-input" class="col-sm-3 form-control-label">{{ __('Title') }}</label>
                                            <div class="col-sm-9">
                                                <textarea
                                                    name="title"
                                                    class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}"
                                                    id="title-input"
                                                    placeholder="{{ __('Job title') }}"
                                                >{{ old('title', $jobBoard->title) }}</textarea>
                                                @if($errors->has('title'))
                                                    <small class="text-danger">{{ $errors->first('title') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="content-input" class="col-sm-3 form-control-label">{{ __('Content') }}</label>
                                            <div class="col-sm-9">
                                                <textarea
                                                    name="content"
                                                    class="form-control {{ $errors->has('content') ? 'is-invalid' : '' }}"
                                                    id="content-input"
                                                    placeholder="{{ __('Job content') }}"
                                                    rows="10"
                                                >{{ old('content', $jobBoard->content) }}</textarea>
                                                @if($errors->has('content'))
                                                    <small class="text-danger">{{ $errors->first('content') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="position-input" class="col-sm-3 form-control-label">{{ __('Position') }}</label>
                                            <div class="col-sm-9">
                                                <textarea
                                                    name="position"
                                                    class="form-control {{ $errors->has('position') ? 'is-invalid' : '' }}"
                                                    id="position-input"
                                                    placeholder="{{ __('Job position') }}"
                                                >{{ old('position', $jobBoard->position) }}</textarea>
                                                @if($errors->has('position'))
                                                    <small class="text-danger">{{ $errors->first('position') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="position-input" class="col-sm-3 form-control-label">{{ __('Executors Count') }}</label>
                                            <div class="col-sm-9">
                                                <input
                                                    type="number"
                                                    min="0"
                                                    name="executor_count"
                                                    class="form-control {{ $errors->has('executor_count') ? 'is-invalid' : '' }}"
                                                    id="executor-count-input"
                                                    value="{{ old('executor_count', $jobBoard->executor_count) }}"
                                                >
                                                @if($errors->has('executor_count'))
                                                    <small class="text-danger">{{ $errors->first('executor_count') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="location-input" class="col-sm-3 form-control-label">
                                                {{ __('Location') }}<span class="text-danger"> *</span>
                                            </label>
                                            <div class="col-sm-9">
                                                <select
                                                    class="form-control {{ $errors->has('location_id') ? 'is-invalid' : '' }}"
                                                    name="location_id"
                                                    id="location-input"
                                                >
                                                    <option disabled selected>{{ __('Select location') }}</option>
                                                    @foreach ($locations as $location)
                                                        <option 
                                                            value="{{ $location->id }}"
                                                            @if($jobBoard->location == $location) selected @endif 
                                                        >{{ $location->name }}</option>
                                                    @endforeach
                                                </select>
                                                @if($errors->has('location_id'))
                                                    <small class="text-danger">{{ $errors->first('location_id') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="group-input" class="col-sm-3 form-control-label">
                                                {{ __('Group') }}
                                            </label>
                                            <div class="col-sm-9">
                                                <select
                                                    class="form-control"
                                                    name="group_id"
                                                    id="group-input"
                                                >
                                                    @foreach ($groups as $group)
                                                        <option 
                                                            value="{{ $group->id }}"
                                                            @if($jobBoard->group == $group) selected @endif 
                                                        >{{ $group->name }}</option>
                                                    @endforeach
                                                </select>
                                                @if($errors->has('groups'))
                                                    <small class="text-danger">{{ $errors->first('groups') }}</small>
                                                @endif
                                            </div>
                                        </div>
                                        @if(Auth::user()->hasRole('super admin'))
                                            <div class="form-group row">
                                                <label for="user-input" class="col-sm-3 form-control-label">
                                                    {{ __('User') }}
                                                </label>
                                                <div class="col-sm-9">
                                                    <select
                                                        class="form-control {{ $errors->has('users') ? 'is-invalid' : '' }}"
                                                        name="user_id"
                                                        id="user-input"
                                                    >
                                                        @foreach($users as $user)
                                                            <option 
                                                                value="{{ $user->id }}"
                                                                @if($jobBoard->user == $user) selected @endif 
                                                            >{{ $user->first_name . ' ' . $user->last_name . ', ' . $user->email }}</option>
                                                        @endforeach
                                                    </select>
                                                    @if($errors->has('users'))
                                                        <small class="text-danger">{{ $errors->first('users') }}</small>
                                                    @endif
                                                </div>
                                            </div>
                                        @endif
                                        <button class="float-right btn btn-primary btn-edit-job">{{ __('Edit') }}</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('external-js')
<script type="application/javascript">
jQuery(document).ready(function () {
    $('.multiselect2-users').select2({
        placeholder: '{{ __('Select users') }}'
    });

    $('.btn-edit-job').on('click', function (e) {
        e.preventDefault();

        $.confirm({
            title: 'Pažnja!',
            content: 'Da li želite da sačuvate izmjene?',
            type: 'warning',
            buttons: {
                confirm: {
                    text: 'OK',
                    btnClass: 'btn-warning',
                    action: function () {
                        $('#form-edit-job').submit();
                    }
                },
                cancel: function () {

                }
            }
        });
    });
});

</script>
@endsection